### ISSUE TITLE
Update Tor Browser to version 14.0.2

### ISSUE THREAD

**Issue by dennysubke** [lkshrk/docker-tor-browser#1]
Why is it not available as tagged image version in packages? (`docker pull ghcr.io/lkshrk/docker-tor-browser:14.0.2`)

**Comment by lkshrk** [comment]
There was an issue with the automated publishing after updating the code. The new version is now also available on dockerhub and future version should be published automatically

**Comment by dennysubke** [comment]
Thank you for this! 😊
